const API_BASE = (window.MATCHPULSE_API_BASE || localStorage.getItem('matchpulse_api_base') || 'https://marokecho-jrrh7cuh.manus.space').replace(/\/$/, '');
const state = { matches: [], english: false, competition: '', status: '', analysisNote: '' };
const $ = (selector) => document.querySelector(selector);
const labels = { ar: { loading: 'جاري تحميل جدول المباريات…', noData: 'لا توجد مباريات حقيقية متاحة حاليًا من المصدر.', error: 'تعذر جلب المباريات. حاول لاحقًا.', analyze: 'تفاصيل المصدر', status: 'الحالة', source: 'المصدر', score: 'النتيجة', summary: 'بيانات المصدر', all: 'كل البطولات', unavailable: 'لا تتوفر احتمالات موثوقة لهذه المباراة حاليًا، لذلك لا يعرض التطبيق توقعات مصطنعة.' }, en: { loading: 'Loading real fixtures…', noData: 'No real fixtures are currently available from the provider.', error: 'Could not fetch fixtures. Try again later.', analyze: 'Source details', status: 'Status', source: 'Source', score: 'Score', summary: 'Source data', all: 'All competitions', unavailable: 'No trustworthy probability data is currently available, so the app does not display fabricated predictions.' } };
const t = () => labels[state.english ? 'en' : 'ar'];
function formatDate(value) { return new Intl.DateTimeFormat(state.english ? 'en' : 'ar-MA', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
function probabilityClass(value) { return value >= 55 ? 'good' : value >= 35 ? 'mid' : 'risk'; }
function visibleMatches() { return state.matches.filter((m) => (!state.competition || m.competition === state.competition) && (!state.status || m.status === state.status)).sort((a, b) => new Date(a.utcDate) - new Date(b.utcDate)); }
function updateCompetitionOptions() { const select = $('#competitionFilter'); const current = state.competition; select.innerHTML = `<option value="">${t().all}</option>` + [...new Set(state.matches.map((m) => m.competition))].sort().map((name) => `<option value="${name}">${name}</option>`).join(''); select.value = current; }
function render() { const matches = visibleMatches(); $('#count').textContent = matches.length; const analysed = matches.filter((m) => m.prediction).length; const live = matches.filter((m) => m.status === 'IN_PLAY').length; $('#summary').textContent = `${t().summary}: ${analysed}/${matches.length}`; $('#metricVisible').textContent = matches.length; $('#metricLive').textContent = live; $('#metricAnalysed').textContent = `${matches.length ? Math.round((analysed / matches.length) * 100) : 0}%`; $('#metricSource').textContent = state.matches.length ? 'football-data.org' : '—'; $('#matches').innerHTML = matches.length ? matches.map((m) => { const score = m.score && (m.score.home !== null || m.score.away !== null) ? ` <small>(${m.score.home ?? '—'} - ${m.score.away ?? '—'})</small>` : ''; return `<tr><td>${formatDate(m.utcDate)}</td><td>${m.competition}</td><td><strong>${m.home}</strong><span class="versus">×</span><strong>${m.away}</strong>${score}</td><td><span class="status">${m.status}</span></td><td><button class="analyze" data-id="${m.id}">${t().analyze}</button></td></tr>`; }).join('') : `<tr><td colspan="5" class="empty">${t().noData}</td></tr>`; document.querySelectorAll('.analyze').forEach((button) => button.addEventListener('click', () => openAnalysis(Number(button.dataset.id)))); }
function openAnalysis(id) { const match = state.matches.find((item) => item.id === id); if (!match) return; const p = match.prediction; const score = match.score && (match.score.home !== null || match.score.away !== null) ? `${match.score.home ?? '—'} - ${match.score.away ?? '—'}` : '—'; $('#modal-title').textContent = `${match.home} × ${match.away}`; const details = `<div class="source-row"><span>${t().source}: <strong>football-data.org · ${match.competition}</strong></span><span>${t().status}: <strong>${match.status}</strong></span><span>${t().score}: <strong>${score}</strong></span></div>`; $('#modal-body').innerHTML = p ? `${details}<div class="probabilities"><div class="prob ${probabilityClass(p.home)}"><span>${t().home}</span><strong>${p.home}%</strong></div><div class="prob ${probabilityClass(p.draw)}"><span>${t().draw}</span><strong>${p.draw}%</strong></div><div class="prob ${probabilityClass(p.away)}"><span>${t().away}</span><strong>${p.away}%</strong></div></div>` : `${details}<p class="method">${state.analysisNote || t().unavailable}</p>`; $('#obta').showModal(); }
async function loadMatches() { $('#notice').textContent = t().loading; try { const response = await fetch(`${API_BASE}/api/trpc/sports.matches?batch=1`); const payload = await response.json(); const data = payload?.[0]?.result?.data?.json; if (!response.ok || !data) throw new Error(payload?.[0]?.error?.json?.message || 'provider unavailable'); state.matches = data.matches || []; state.analysisNote = data.analysisNote || ''; updateCompetitionOptions(); $('#notice').textContent = data.configured ? `${data.source} · ${data.fetchedAt ? formatDate(data.fetchedAt) : ''}${data.cached ? ' · مخزّن مؤقتًا' : ''}` : data.message || t().noData; } catch { state.matches = []; state.analysisNote = ''; $('#notice').textContent = t().error; } render(); }
$('#refresh').addEventListener('click', loadMatches); $('#competitionFilter').addEventListener('change', (event) => { state.competition = event.target.value; render(); }); $('#statusFilter').addEventListener('change', (event) => { state.status = event.target.value; render(); }); $('#close').addEventListener('click', () => $('#obta').close()); $('#language').addEventListener('click', () => { state.english = !state.english; document.documentElement.lang = state.english ? 'en' : 'ar'; document.documentElement.dir = state.english ? 'ltr' : 'rtl'; $('#language').textContent = state.english ? 'العربية' : 'English'; updateCompetitionOptions(); loadMatches(); });
loadMatches();
